import { ClothingItem } from '@/types/firebase';

export const MOCK_CLOTHES: ClothingItem[] = [
  {
    id: '1',
    userId: '1',
    name: 'T-shirt en coton bio',
    type: 'tops',
    brand: 'Patagonia',
    colors: ['Blanc', 'Noir'],
    seasons: ['Printemps', 'Été', 'Automne'],
    imageUrl: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500&q=80',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    userId: '1',
    name: 'Jean Selvedge',
    type: 'bottoms',
    brand: 'A.P.C.',
    colors: ['Bleu'],
    seasons: ['Toutes'],
    imageUrl: 'https://images.unsplash.com/photo-1602293589930-45a9ec88e5c3?w=500&q=80',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    userId: '1',
    name: 'Robe d\'été à fleurs',
    type: 'dresses',
    brand: 'Sézane',
    colors: ['Multicolore', 'Rose'],
    seasons: ['Été'],
    imageUrl: 'https://images.unsplash.com/photo-1594744806422-7217c3777559?w=500&q=80',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    userId: '1',
    name: 'Baskets en cuir blanc',
    type: 'shoes',
    brand: 'Veja',
    colors: ['Blanc'],
    seasons: ['Toutes'],
    imageUrl: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=500&q=80',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    userId: '1',
    name: 'Sac à dos en toile',
    type: 'accessories',
    brand: 'Fjällräven',
    colors: ['Gris'],
    seasons: ['Toutes'],
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb68c6a62?w=500&q=80',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '6',
    userId: '1',
    name: 'Pull en laine mérinos',
    type: 'tops',
    brand: 'Uniqlo',
    colors: ['Gris', 'Noir'],
    seasons: ['Automne', 'Hiver'],
    imageUrl: 'https://images.unsplash.com/photo-1616258417212-7422a5786c4f?w=500&q=80',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '7',
    userId: '1',
    name: 'Pantalon chino beige',
    type: 'bottoms',
    brand: 'Dockers',
    colors: ['Beige'],
    seasons: ['Printemps', 'Été', 'Automne'],
    imageUrl: 'https://images.unsplash.com/photo-1605518216944-70f906a23995?w=500&q=80',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '8',
    userId: '1',
    name: 'Sandales en cuir',
    type: 'shoes',
    brand: 'Birkenstock',
    colors: ['Marron'],
    seasons: ['Été'],
    imageUrl: 'https://images.unsplash.com/photo-1603487742131-419142953b88?w=500&q=80',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
   {
    id: '9',
    userId: '1',
    name: 'Écharpe en cachemire',
    type: 'accessories',
    brand: 'Eric Bompard',
    colors: ['Gris'],
    seasons: ['Hiver'],
    imageUrl: 'https://images.unsplash.com/photo-1542359649-31e03cdde49d?w=500&q=80',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '10',
    userId: '1',
    name: 'Chemise en lin',
    type: 'tops',
    brand: 'COS',
    colors: ['Blanc'],
    seasons: ['Printemps', 'Été'],
    imageUrl: 'https://images.unsplash.com/photo-1621072151979-39b06f54c375?w=500&q=80',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '11',
    userId: '1',
    name: 'Jupe midi plissée',
    type: 'bottoms',
    brand: 'Zara',
    colors: ['Rose', 'Rouge'],
    seasons: ['Printemps', 'Été'],
    imageUrl: 'https://images.unsplash.com/photo-1583496661160-fb5207753051?w=500&q=80',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '12',
    userId: '1',
    name: 'Bottes en daim',
    type: 'shoes',
    brand: 'Clarks',
    colors: ['Marron'],
    seasons: ['Automne', 'Hiver'],
    imageUrl: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=500&q=80',
    createdAt: new Date(),
    updatedAt: new Date(),
  }
]; 